---
abstract: 'Delay I18N translation until a variable is stringified'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: I18N-String
requires:
  Carp: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/I18N-String/issues
  repository: git://github.com/clintongormley/I18N-String.git
version: 0.01
